version: "3.8"

services:
  apache:
    build:
      context: ./lamp
      dockerfile: Dockerfile
    image: ${APP_IMAGE}
    #restart: always
    container_name: ${APP_CONTAINER}
    working_dir: /var/www/app
    volumes:
      - ../:/var/www/app
      - ${APP_CONFIG_05}:/var/log/apache2
      - ${APP_CONFIG_03}:/etc/apache2/httpd.conf
      - ${APP_CONFIG_02}:/etc/php7/php.ini
      - ${APP_CONFIG_04}:/etc/freetds.conf
    ports:
      - ${APP_PORT_01}:80
    networks:
      - network_01
    depends_on:
      - redis
    entrypoint:
      - sh
      - ./container-alpine/entrypoint
  
  redis:
    image: redis:latest
    container_name: ${REDIS_CONTAINER}
    #restart: always
   # command: ["/usr/local/etc/redis/redis.conf"]
   # volumes:
    #  - ${REDIS_CONFIG_01}:/usr/local/etc/redis/redis.conf
    #ports:
    #  - ${REDIS_PORT_01}:6379
    networks:
      - network_01

networks:
  network_01:
    external: true
    driver: bridge
    name: ${APP_NETWORK_01}

